apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  type: NodePort
  selector:
    app: postgres
  ports:
    - port: 5432         # Puerto en el servicio
      targetPort: 5432   # Puerto en el contenedor
      nodePort: 30015    # Puerto expuesto en el nodo (solo para NodePort)